#! /bin/sh

file=$1

if [ ! -r "$file" ]
then
    echo "can't open $file"
    exit 1
fi

psql --quiet apply-pace <<!
drop table email_history;
drop table evid_info;
drop table json;
drop table knex_migrations;
drop table knex_migrations_lock;
drop table pcodes;
drop table seq;
drop table sessions;
drop table vars;
!

gunzip < $file | psql --quiet apply-pace

