#! /usr/bin/env node
/* -*- mode:javascript -*- */

const pwjs = require ('./pwjs');
var argv = require('minimist')(process.argv.slice(2));

if (argv._.length != 1) {
  printf ("usage: getvar NAME\n");
  process.exit (1);
}

var name = argv._[0];

async function doit () {
  let res = await pwjs.query ("select val"
			      +" from vars"
			      +" where var = $1",
			      [ name ]);
  let val = null;
  if (res.length > 0) {
    val = res[0].val;
  }

  printf ("%s\n", val);

  await pwjs.postgres_finish ();

}

doit();



