#! /usr/bin/php
<?php

require_once ("cli.php");

if (($str = @$argv[1]) == "") {
    printf ("usage: lookup str\n");
    exit (1);
}

$arr = lookup_individual ($str);
foreach ($arr as $p) {
    printf ("%-6d %8.3f %8.3f %s\n", $p->perf_id, $p->score, $p->pct, $p->name);
}

