#! /usr/bin/env python3

import os
import sys
import re
import datetime

if 'PSITE_DIR' in os.environ:
    psite_dir = os.environ['PSITE_DIR']
else:
    psite_dir = "{}/psite".format(os.environ['HOME'])

sys.path.append(psite_dir)

import psite
import db

db = db.get_db()
cur = db['cursor']

data = {}

x_year = datetime.date.today().year

cur.execute ("select ts, fest_year, val from json where test_flag = 0")
while True:
    row = cur.fetchone()
    if row is None:
        break
    (ts, fest_year, val) = row
    if val[0] != "{":
        continue

    if fest_year not in data:
        data[fest_year] = {}
    
    key = f'{ts.year}-{ts.month}-{ts.day}'
    if ts.month == 9 or ts.month == 10:
        key = f'{ts.month:02d}-{ts.day:02d}'
        if key not in data[fest_year]:
            data[fest_year][key] = 0
        data[fest_year][key] += 1

cfg = psite.get_cfg()

def data_filename(fest_year):
    return "{}/TMP.{}.dat".format(cfg['aux_dir'], fest_year)

for fest_year in data.keys():
    acc = 0
    filename = data_filename(fest_year)
    try:
        os.remove(filename)
    except:
        pass
    with open(filename, "w") as outf:
        count = 0
        for key in sorted(list(data[fest_year])):
            if key in data[fest_year]:
                count = data[fest_year][key]
                acc = acc + count
                x = f'{x_year}-{key}'
                print(x, acc, file=outf)

gprc = "{}/TMP.gprc".format(cfg['aux_dir'])
output = "{}/rate.png".format(cfg['aux_dir'])

try:
    os.remove(gprc)
except:
    pass

try:
    os.remove(output)
except:
    pass

with open(gprc, "w") as outf:
    outf.write("set terminal png\n")
    outf.write("set output \"{}\"\n".format(output));
    outf.write ("set term png size 1024, 768\n");
    
    outf.write("set xdata time\n")
    outf.write("set timefmt \"%Y-%m-%d\"\n")
    outf.write(f'set xrange ["{x_year}-09-01":"{x_year}-10-31"]\n')
    outf.write("set format x \"%m/%d\"\n")
    outf.write("set style data lines\n")
    outf.write("set xlabel \"date\"\n")
    outf.write("set ylabel \"number of applications\n")

    cmd = "plot "
    need_comma = False
    for fest_year in data.keys():
        if need_comma == True:
            cmd += ","
        need_comma = True
        filename = data_filename(fest_year)
        cmd += "\"{}\" using 1:2 title '{}'".format(filename, fest_year)
    cmd += "\n"
    outf.write(cmd)

cmd = "gnuplot {}".format(gprc)
print(cmd)
os.system(cmd)

print(output)
