#! /bin/sh

# exec mysql --login-path=neffa -A --database=neffa_pdb "$@"

exec mysql --user pace_willisson \
     --host=neffaprog.neffa.dreamhosters.com \
     --password=`cat ~/aux/neffadb_passwd` \
     neffa_pdb
