#! /usr/bin/php
<?php

require_once ("cli.php");

if (($pw = @$argv[1]) == "") {
    printf ("usage: setpw password\n");
    exit (1);
}

setvar ("admin_passwd", password_hash ($pw, PASSWORD_DEFAULT));
do_commits ();


