#! /usr/bin/env node
/* -*- mode:javascript -*- */

const pwjs = require ('./pwjs');
var argv = require('minimist')(process.argv.slice(2));

if (argv._.length != 2) {
  printf ("usage: setvar NAME VAL\n");
  process.exit (1);
}

var name = argv._[0];
var val = argv._[1];

async function doit () {
  let res = await pwjs.query ("select val"
			      +" from vars"
			      +" where var = $1",
			      [ name ]);
  if (res.length == 0) {
    await pwjs.query ("insert into vars (var, val)"
		      +" values ($1, $2)",
		      [ name, val ]);
  } else {
    await pwjs.query ("update vars set val = $1 where var = $2",
		      [ val, name ]);
  }

  await pwjs.postgres_finish ();

}

doit();



